language: node_js
notifications:
  email: false
matrix:
  include:
    - node_js: 8
      script:
        - npm t
        - $(npm bin)/codecov
    - node_js: 10
      script:
        - npm t
    - node_js: 12
      script:
        - npm t
