language: node_js
notifications:
  email: false
if: type = pull_request
matrix:
  include:
    - node_js: 8
      script:
        - npm t
        - npm run coverage
    - node_js: 10
      script:
        - npm t
    - node_js: 12
      script:
        - npm t
